<?php

namespace Database\Seeders;

use App\Models\Pais;
use App\Models\Estado;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paises = [
            [1, 'AD', 'AND', 'ANDORRA', 2, 1],
            [2, 'AE', 'ARE', 'EMIRATOS ARABES UNIDOS', 2, 1],
            [3, 'AF', 'AFG', 'AFGANISTAN', 2, 1],
            [4, 'AG', 'ATG', 'ANTIGUA Y BARBUDA', 2, 1],
            [5, 'AI', 'AIA', 'ANGUILA', 2, 1],
            [6, 'AL', 'ALB', 'ALBANIA', 2, 1],
            [7, 'AM', 'ARM', 'ARMENIA', 2, 1],
            [8, 'AN', 'ANT', 'ANTILLAS NEERLANDESAS', 2, 1],
            [9, 'AO', 'AGO', 'ANGOLA', 2, 1],
            [10, 'AQ', '', 'ANTARTIDA', 2, 1],
            [11, 'AR', 'ARG', 'ARGENTINA', 2, 1],
            [12, 'AS', 'ASM', 'SAMOA AMERICANA', 2, 1],
            [13, 'AT', 'AUT', 'AUSTRIA', 2, 1],
            [14, 'AU', 'AUS', 'AUSTRALIA', 2, 1],
            [15, 'AW', 'ABW', 'ARUBA', 2, 1],
            [16, 'AZ', 'AZE', 'AZERBAIYAN', 2, 1],
            [17, 'BA', 'BIH', 'BOSNIA-HERZEGOVINA', 2, 1],
            [18, 'BB', 'BRB', 'BARBADOS', 2, 1],
            [19, 'BD', 'BGD', 'BANGLADESH', 2, 1],
            [20, 'BE', 'BEL', 'BELGICA', 2, 1],
            [21, 'BF', 'BFA', 'BURKINA FASO', 2, 1],
            [22, 'BG', 'BGR', 'BULGARIA', 2, 1],
            [23, 'BH', 'BHR', 'BAHREIN', 2, 1],
            [24, 'BI', 'BDI', 'BURUNDI', 2, 1],
            [25, 'BJ', 'BEN', 'BENIN', 2, 1],
            [26, 'BM', 'BMU', 'BERMUDAS', 2, 1],
            [27, 'BN', 'BRN', 'BRUNEI', 2, 1],
            [28, 'BO', 'BOL', 'BOLIVIA', 2, 1],
            [29, 'BQ', '', 'PAISES, BAJOS [PARTE CARIBEÑA]', 2, 1],
            [30, 'BR', 'BRA', 'BRASIL', 2, 1],
            [31, 'BS', 'BHS', 'BAHAMAS', 2, 1],
            [32, 'BT', 'BTN', 'BUTAN', 2, 1],
            [33, 'BV', 'BVT', 'BOUVET, ISLA', 2, 1],
            [34, 'BW', 'BWA', 'BOTSUANA', 2, 1],
            [35, 'BY', 'BLR', 'BIELORRUSIA', 2, 1],
            [36, 'BZ', 'BLZ', 'BELICE', 2, 1],
            [37, 'CA', 'CAN', 'CANADA', 2, 1],
            [38, 'CC', 'CCK', 'COCOS', 2, 1],
            [39, 'CD', 'COD', 'CONGO, REPUBLICA DEMOCRATICA', 2, 1],
            [40, 'CF', 'CAF', 'CENTROAFRICANA, REPUBLICA', 2, 1],
            [41, 'CG', 'COG', 'CONGO', 2, 1],
            [42, 'CH', 'CHE', 'SUIZA', 2, 1],
            [43, 'CI', 'CIV', 'COSTA DE MARFIL', 2, 1],
            [44, 'CK', 'COK', 'COOK, ISLAS', 2, 1],
            [45, 'CL', 'CHL', 'CHILE', 2, 1],
            [46, 'CM', 'CMR', 'CAMERUN', 2, 1],
            [47, 'CN', 'CHN', 'CHINA', 2, 1],
            [48, 'CO', 'COL', 'COLOMBIA', 2, 1],
            [49, 'CR', 'CRI', 'COSTA RICA', 2, 1],
            [50, 'CU', 'CUB', 'CUBA', 2, 1],
            [51, 'CV', 'CPV', 'CABO VERDE, REPUBLICA DE', 2, 1],
            [52, 'CW', 'CUW', 'CURAÇAO', 2, 1],
            [53, 'CX', 'CXR', 'NAVIDAD, ISLA', 2, 1],
            [54, 'CY', 'CYP', 'CHIPRE', 2, 1],
            [55, 'CZ', 'CZE', 'CHECA, REPUBLICA', 2, 1],
            [56, 'DE', 'DEU', 'ALEMANIA', 2, 1],
            [57, 'DJ', 'DJI', 'YIBUTI', 2, 1],
            [58, 'DK', 'DNK', 'DINAMARCA', 2, 1],
            [59, 'DM', 'DMA', 'DOMINICA', 2, 1],
            [60, 'DO', 'DOM', 'DOMINICANA, REPUBLICA', 2, 1],
            [61, 'DZ', 'DZA', 'ARGELIA', 2, 1],
            [62, 'EC', 'ECU', 'ECUADOR', 2, 1],
            [63, 'EE', 'EST', 'ESTONIA', 2, 1],
            [64, 'EG', 'EGY', 'EGIPTO', 2, 1],
            [65, 'EH', 'ESH', 'SAHARA OCCIDENTAL', 2, 1],
            [66, 'ER', 'ERI', 'ERITREA', 2, 1],
            [67, 'ES', 'ESP', 'ESPAÑA', 1, 2],
            [68, 'ET', 'ETH', 'ETIOPIA', 2, 1],
            [69, 'FI', 'FIN', 'FINLANDIA', 2, 1],
            [70, 'FJ', 'FJI', 'FIYI', 2, 1],
            [71, 'FK', 'FLK', 'MALVINAS, ISLAS', 2, 1],
            [72, 'FM', 'FSM', 'MICRONESIA', 2, 1],
            [73, 'FO', 'FRO', 'FEROE, ISLAS', 2, 1],
            [74, 'FR', 'FRA', 'FRANCIA', 2, 1],
            [75, 'GA', 'GAB', 'GABON', 2, 1],
            [76, 'GB', 'GBR', 'REINO UNIDO', 2, 1],
            [77, 'GD', 'GRD', 'GRANADA', 2, 1],
            [78, 'GE', 'GEO', 'GEORGIA', 2, 1],
            [79, 'GG', 'GGY', 'GUERNESEY', 2, 1],
            [80, 'GH', 'GHA', 'GHANA', 2, 1],
            [81, 'GI', 'GIB', 'GIBRALTAR', 2, 1],
            [82, 'GL', 'GRL', 'GROENLANDIA', 2, 1],
            [83, 'GM', 'GMB', 'GAMBIA', 2, 1],
            [84, 'GN', 'GIN', 'GUINEA', 2, 1],
            [85, 'GQ', 'GNQ', 'GUINEA ECUATORIAL', 2, 1],
            [86, 'GR', 'GRC', 'GRECIA', 2, 1],
            [87, 'GS', 'SGS', 'GEORGIA DEL SUR', 2, 1],
            [88, 'GT', 'GTM', 'GUATEMALA', 2, 1],
            [89, 'GU', 'GUM', 'GUAM', 2, 1],
            [90, 'GW', 'GNB', 'GUINEA-BISSAU', 2, 1],
            [91, 'GY', 'GUY', 'GUYANA', 2, 1],
            [92, 'HK', 'HKG', 'HONG-KONG', 2, 1],
            [93, 'HM', 'HMD', 'HEARD Y MCDONALD, ISLAS', 2, 1],
            [94, 'HN', 'HND', 'HONDURAS', 2, 1],
            [95, 'HR', 'HRV', 'CROACIA', 2, 1],
            [96, 'HT', 'HTI', 'HAITI', 2, 1],
            [97, 'HU', 'HUN', 'HUNGRIA', 2, 1],
            [98, 'ID', 'IDN', 'INDONESIA', 2, 1],
            [99, 'IE', 'IRL', 'IRLANDA', 2, 1],
            [100, 'IL', 'ISR', 'ISRAEL', 2, 1],
            [101, 'IM', 'IMN', 'ISLA DE MAN', 2, 1],
            [102, 'IN', 'IND', 'INDIA', 2, 1],
            [103, 'IO', 'IOT', 'OCEANO INDICO, TERRI.BRITANICO', 2, 1],
            [104, 'IQ', 'IRQ', 'IRAQ', 2, 1],
            [105, 'IR', 'IRN', 'IRAN', 2, 1],
            [106, 'IS', 'ISL', 'ISLANDIA', 2, 1],
            [107, 'IT', 'ITA', 'ITALIA', 2, 1],
            [108, 'JE', 'JEY', 'JERSEY', 2, 1],
            [109, 'JM', 'JAM', 'JAMAICA', 2, 1],
            [110, 'JO', 'JOR', 'JORDANIA', 2, 1],
            [111, 'JP', 'JPN', 'JAPON', 2, 1],
            [112, 'KE', 'KEN', 'KENIA', 2, 1],
            [113, 'KG', 'KGZ', 'KIRGUISTAN', 2, 1],
            [114, 'KH', 'KHM', 'CAMBOYA', 2, 1],
            [115, 'KI', 'KIR', 'KIRIBATI', 2, 1],
            [116, 'KM', 'COM', 'COMORAS', 2, 1],
            [117, 'KN', 'KNA', 'SAN CRISTOBAL Y NIEVES', 2, 1],
            [118, 'KP', 'PRK', 'COREA DEL NORTE', 2, 1],
            [119, 'KR', 'KOR', 'COREA DEL SUR', 2, 1],
            [120, 'KW', 'KWT', 'KUWAIT', 2, 1],
            [121, 'KY', 'CYM', 'CAIMAN, ISLAS', 2, 1],
            [122, 'KZ', 'KAZ', 'KAZAJSTAN', 2, 1],
            [123, 'LA', 'LAO', 'LAOS', 2, 1],
            [124, 'LB', 'LBN', 'LIBANO', 2, 1],
            [125, 'LC', 'LCA', 'SANTA LUCIA', 2, 1],
            [126, 'LI', 'LIE', 'LIECHTENSTEIN', 2, 1],
            [127, 'LK', 'LKA', 'SRI LANKA', 2, 1],
            [128, 'LR', 'LBR', 'LIBERIA', 2, 1],
            [129, 'LS', 'LSO', 'LESOTHO', 2, 1],
            [130, 'LT', 'LTU', 'LITUANIA', 2, 1],
            [131, 'LU', 'LUX', 'LUXEMBURGO', 2, 1],
            [132, 'LV', 'LVA', 'LETONIA', 2, 1],
            [133, 'LY', 'LBY', 'LIBIA', 2, 1],
            [134, 'MA', 'MAR', 'MARRUECOS', 2, 1],
            [135, 'MC', 'MCO', 'MONACO', 2, 1],
            [136, 'MD', 'MDA', 'MOLDAVIA', 2, 1],
            [137, 'ME', 'MNE', 'MONTENEGRO', 2, 1],
            [138, 'MG', 'MDG', 'MADAGASCAR', 2, 1],
            [139, 'MH', 'MHL', 'MARSHALL, ISLAS', 2, 1],
            [140, 'MK', 'MKD', 'MACEDONIA', 2, 1],
            [141, 'ML', 'MLI', 'MALI', 2, 1],
            [142, 'MM', 'MMR', 'MYANMAR', 2, 1],
            [143, 'MN', 'MNG', 'MONGOLIA', 2, 1],
            [144, 'MO', 'MAC', 'MACAO', 2, 1],
            [145, 'MP', 'MNP', 'MARIANAS DEL NORTE, ISLAS', 2, 1],
            [146, 'MR', 'MRT', 'MAURITANIA', 2, 1],
            [147, 'MS', 'MSR', 'MONTSERRAT', 2, 1],
            [148, 'MT', 'MLT', 'MALTA', 2, 1],
            [149, 'MU', 'MUS', 'MAURICIO', 2, 1],
            [150, 'MV', 'MDV', 'MALDIVAS', 2, 1],
            [151, 'MW', 'MWI', 'MALAWI', 2, 1],
            [152, 'MX', 'MEX', 'MEXICO', 2, 1],
            [153, 'MY', 'MYS', 'MALASIA', 2, 1],
            [154, 'MZ', 'MOZ', 'MOZAMBIQUE', 2, 1],
            [155, 'NA', 'NAM', 'NAMIBIA', 2, 1],
            [156, 'NC', 'NCL', 'NUEVA CALEDONIA', 2, 1],
            [157, 'NE', 'NER', 'NIGER', 2, 1],
            [158, 'NF', 'NFK', 'NORFOLK, ISLA', 2, 1],
            [159, 'NG', 'NGA', 'NIGERIA', 2, 1],
            [160, 'NI', 'NIC', 'NICARAGUA', 2, 1],
            [161, 'NL', 'NLD', 'PAISES BAJOS', 2, 1],
            [162, 'NO', 'NOR', 'NORUEGA', 2, 1],
            [163, 'NP', 'NPL', 'NEPAL', 2, 1],
            [164, 'NR', 'NRU', 'NAURU', 2, 1],
            [165, 'NU', 'NIU', 'NIUE, ISLA', 2, 1],
            [166, 'NZ', 'NZL', 'NUEVA ZELANDA', 2, 1],
            [167, 'OM', 'OMN', 'OMAN', 2, 1],
            [168, 'PA', 'PAN', 'PANAMA', 2, 1],
            [169, 'PE', 'PER', 'PERU', 2, 1],
            [170, 'PF', 'PYF', 'POLINESIA FRANCESA', 2, 1],
            [171, 'PG', 'PNG', 'PAPUA NUEVA GUINEA', 2, 1],
            [172, 'PH', 'PHL', 'FILIPINAS', 2, 1],
            [173, 'PK', 'PAK', 'PAKISTAN', 2, 1],
            [174, 'PL', 'POL', 'POLONIA', 2, 1],
            [175, 'PM', 'SPM', 'SAN PEDRO Y MIQUELON', 2, 1],
            [176, 'PN', 'PCN', 'PITCAIRN', 2, 1],
            [177, 'PR', 'PRI', 'PUERTO RICO', 2, 1],
            [178, 'PS', 'PSE', 'TERRITORIO PALESTINO OCUPADO', 2, 1],
            [179, 'PT', 'PRT', 'PORTUGAL', 2, 1],
            [180, 'PW', 'PLW', 'PALAU', 2, 1],
            [181, 'PY', 'PRY', 'PARAGUAY', 2, 1],
            [182, 'QA', 'QAT', 'QATAR', 2, 1],
            [183, 'QU', '', 'OTROS, PAISES NO RELACIONADOS', 2, 1],
            [184, 'RO', 'ROU', 'RUMANIA', 2, 1],
            [185, 'RS', 'SRB', 'SERBIA', 2, 1],
            [186, 'RU', 'RUS', 'RUSIA', 2, 1],
            [187, 'RW', 'RWA', 'RUANDA', 2, 1],
            [188, 'SA', 'SAU', 'ARABIA SAUDI', 2, 1],
            [189, 'SB', 'SLB', 'SALOMON, ISLAS', 2, 1],
            [190, 'SC', 'SYC', 'SEYCHELLES', 2, 1],
            [191, 'SD', 'SDN', 'SUDAN', 2, 1],
            [192, 'SE', 'SWE', 'SUECIA', 2, 1],
            [193, 'SG', 'SGP', 'SINGAPUR', 2, 1],
            [194, 'SH', 'SHN', 'SANTA ELENA', 2, 1],
            [195, 'SI', 'SVN', 'ESLOVENIA', 2, 1],
            [196, 'SK', 'SVK', 'ESLOVAQUIA', 2, 1],
            [197, 'SL', 'SLE', 'SIERRA LEONA', 2, 1],
            [198, 'SM', 'SMR', 'SAN MARINO', 2, 1],
            [199, 'SN', 'SEN', 'SENEGAL', 2, 1],
            [200, 'SO', 'SOM', 'SOMALIA', 2, 1],
            [201, 'SR', 'SUR', 'SURINAM', 2, 1],
            [202, 'SS', 'SSD', 'SUDAN DEL SUR', 2, 1],
            [203, 'ST', 'STP', 'SANTO TOME Y PRINCIPE', 2, 1],
            [204, 'SV', 'SLV', 'SALVADOR, EL', 2, 1],
            [205, 'SX', '', 'SAN, MARTIN', 2, 1],
            [206, 'SY', 'SYR', 'SIRIA', 2, 1],
            [207, 'SZ', 'SWZ', 'SUAZILANDIA', 2, 1],
            [208, 'TC', 'TCA', 'TURCAS Y CAICOS, ISLAS', 2, 1],
            [209, 'TD', 'TCD', 'CHAD', 2, 1],
            [210, 'TF', 'ATF', 'TIERRAS AUSTRALES FRANCESAS', 2, 1],
            [211, 'TG', 'TGO', 'TOGO', 2, 1],
            [212, 'TH', 'THA', 'TAILANDIA', 2, 1],
            [213, 'TJ', 'TJK', 'TAYIKISTAN', 2, 1],
            [214, 'TK', 'TKL', 'TOKELAU, ISLAS', 2, 1],
            [215, 'TL', 'TLS', 'TIMOR LESTE', 2, 1],
            [216, 'TM', 'TKM', 'TURKMENISTAN', 2, 1],
            [217, 'TN', 'TUN', 'TUNEZ', 2, 1],
            [218, 'TO', 'TON', 'TONGA', 2, 1],
            [219, 'TR', 'TUR', 'TURQUIA', 2, 1],
            [220, 'TT', 'TTO', 'TRINIDAD Y TOBAGO', 2, 1],
            [221, 'TV', 'TUV', 'TUVALU', 2, 1],
            [222, 'TW', 'TWN', 'TAIWAN', 2, 1],
            [223, 'TZ', 'TZA', 'TANZANIA', 2, 1],
            [224, 'UA', 'UKR', 'UCRANIA', 2, 1],
            [225, 'UG', 'UGA', 'UGANDA', 2, 1],
            [226, 'UM', '', 'MENORES, ALEJADAS EE.UU, ISLAS', 2, 1],
            [227, 'US', 'USA', 'ESTADOS UNIDOS DE AMERICA', 2, 1],
            [228, 'UY', 'URY', 'URUGUAY', 2, 1],
            [229, 'UZ', 'UZB', 'UZBEKISTAN', 2, 1],
            [230, 'VA', 'VAT', 'VATICANO, CIUDAD DEL', 2, 1],
            [231, 'VC', 'VCT', 'SAN VICENTE Y LAS GRANADINAS', 2, 1],
            [232, 'VE', 'VEN', 'VENEZUELA', 2, 1],
            [233, 'VG', 'VGB', 'VIRGENES BRITANICAS, ISLAS', 2, 1],
            [234, 'VI', 'VIR', 'VIRGENES DE LOS EE.UU, ISLAS', 2, 1],
            [235, 'VN', 'VNM', 'VIETNAM', 2, 1],
            [236, 'VU', 'VUT', 'VANUATU', 2, 1],
            [237, 'WF', 'WLF', 'WALLIS Y FUTUNA, ISLAS', 2, 1],
            [238, 'WS', 'WSM', 'SAMOA', 2, 1],
            [239, 'YE', 'YEM', 'YEMEN', 2, 1],
            [240, 'YT', 'MYT', 'MAYOTTE', 2, 1],
            [241, 'ZA', 'ZAF', 'SUDAFRICA', 2, 1],
            [242, 'ZM', 'ZMB', 'ZAMBIA', 2, 1],
            [243, 'ZW', 'ZWE', 'ZIMBABUE', 0, 1],
        ];

        Schema::disableForeignKeyConstraints();
        Pais::truncate();
        Schema::enableForeignKeyConstraints();


        foreach ($paises as $pais) {
            Pais::create([
                'codigo2' => $pais[1],
                'codigo3' => $pais[2],
                'nombre' => $pais[3],
                'estado_id' => Estado::ESTADO_ACTIVO,                
            ]);
        }
        Pais::whereIn('id', [67,179,183])->update(['orden'=> 10]);
    }
}
