<?php
namespace Database\Seeders;

use App\Models\TipoVia;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class TipoViaSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Schema::disableForeignKeyConstraints();
        TipoVia::truncate();
        Schema::enableForeignKeyConstraints();


        $tiposdevia = [
            ['.    ', '. ', '                                                                       '],
            ['RPLCT', 'XX', '                                                                       '],
            ['CALL ', 'XX', 'CALL                                                                   '],
            ['PTJA ', 'XX', 'PTJA                                                                   '],
            ['ESCU ', 'XX', 'ESCU                                                                   '],
            ['MOLI ', 'XX', 'MOLI                                                                   '],
            ['COMPX', 'XX', 'COMPX                                                                  '],
            ['BDOR ', 'XX', '                                                                       '],
            ['GRNJA', 'XX', '                                                                       '],
            ['CALLI', 'XX', '                                                                       '],
            ['TRVSA', 'XX', '                                                                       '],
            ['CAMP ', 'XX', '                                                                       '],
            ['TUNEL', 'XX', '                                                                       '],
            ['CRSIA', 'XX', '                                                                       '],
            ['CLLJO', 'XX', '                                                                       '],
            ['SLIDA', 'XX', '                                                                       '],
            ['PLLO ', 'XX', '                                                                       '],
            ['CRRO ', 'XX', '                                                                       '],
            ['PLCNA', 'XX', '                                                                       '],
            ['CAL. ', 'XX', '                                                                       '],
            ['CNDA ', 'XX', '                                                                       '],
            ['VNERA', 'XX', '                                                                       '],
            ['CORDL', 'XX', '                                                                       '],
            ['GJA  ', 'XX', '                                                                       '],
            ['TUNEL', 'XX', '                                                                       '],
            ['RAMPS', 'RP', 'RAMPAS                                                                 '],
            ['ACCE ', 'AC', 'ACCES                                                                  '],
            ['ACCES', 'AC', 'ACCESO                                                                 '],
            ['ACEQ ', 'AE', 'ACEQUIA                                                                '],
            ['ACERA', 'AA', 'ACERA                                                                  '],
            ['ALAM ', 'AL', 'ALAMEDA                                                                '],
            ['ALDAP', 'CT', 'ALDAPA                                                                 '],
            ['ALDEA', 'AD', 'ALDEA                                                                  '],
            ['ALQUE', 'AQ', 'ALQUERIA                                                               '],
            ['ALTO ', 'AT', 'ALTO                                                                   '],
            ['ANDAD', 'AN', 'ANDADOR                                                                '],
            ['ANGTA', 'AG', 'ANGOSTA                                                                '],
            ['APDRO', 'AO', 'APEADEIRO                                                              '],
            ['APDRO', 'AO', 'APEADERO                                                               '],
            ['APTES', 'AP', 'APARTAMENTS                                                            '],
            ['APTOS', 'AP', 'APARTAMENTOS                                                           '],
            ['ARB  ', 'AB', 'ARBOLEDA                                                               '],
            ['ARRAL', 'AR', 'ARRABAL                                                                '],
            ['ARREK', 'AY', 'ERREKA                                                                 '],
            ['ARRY ', 'AY', 'ARROYO                                                                 '],
            ['ASSEG', 'AS', 'ASSEGADOR                                                              '],
            ['ATAJO', 'AJ', 'ATAJO                                                                  '],
            ['ATAL ', 'AJ', 'ATALL                                                                  '],
            ['ATALL', 'AJ', 'ATALLO                                                                 '],
            ['ATZUC', 'AZ', 'ATZUCAT                                                                '],
            ['AUTO ', 'AU', 'AUTOPISTA                                                              '],
            ['AUTOV', 'AI', 'AUTOVIA                                                                '],
            ['AUZO ', 'BO', 'AUZO                                                                   '],
            ['AUZOT', 'BA', 'AUZOTEGI                                                               '],
            ['AUZUN', 'BO', 'AUZUNEA                                                                '],
            ['AV   ', 'AV', 'AV                                                                     '],
            ['AVDA ', 'AV', 'AVENIDA                                                                '],
            ['AVGDA', 'AV', 'AVINGUDA                                                               '],
            ['AVIA ', 'AI', 'AUTOVIA                                                                '],
            ['BALNR', 'BN', 'BALNEARIO                                                              '],
            ['BARDA', 'BA', 'BARRIADA                                                               '],
            ['BARRI', 'BO', 'BARRI                                                                  '],
            ['BARRO', 'BO', 'BARRIO                                                                 '],
            ['BDA  ', 'BJ', 'BAIXADA                                                                '],
            ['BELNA', 'BE', 'BELENA                                                                 '],
            ['BIDE ', 'VI', 'BIDE                                                                   '],
            ['BIDEB', 'GL', 'BIDEBIETA                                                              '],
            ['BJADA', 'BJ', 'BAJADA                                                                 '],
            ['BLOC ', 'BL', 'BLOC                                                                   '],
            ['BLQUE', 'BL', 'BLOQUE                                                                 '],
            ['BQLLO', 'BQ', 'BARRANQUIL                                                             '],
            ['BRANC', 'BR', 'BARRANCO                                                               '],
            ['BRDLA', 'BD', 'BARREDUELA                                                             '],
            ['BRZAL', 'BZ', 'BRAZAL                                                                 '],
            ['BSRIA', 'BS', 'BASERRIA                                                               '],
            ['BULEV', 'BV', 'BULEVAR                                                                '],
            ['BV   ', 'BV', 'BULEVAR                                                                '],
            ['C    ', 'C ', 'C                                                                      '],
            ['C.H. ', 'KH', 'CMNO HONDO                                                             '],
            ['C.N. ', 'KN', 'CMNO NUEVO                                                             '],
            ['C.V. ', 'KV', 'CMNO VIEJO                                                             '],
            ['C/   ', 'C/', 'C/                                                                     '],
            ['CÑADA', 'CÑ', 'CAÑADA                                                                 '],
            ['CALLE', 'CL', 'CALLE                                                                  '],
            ['CAMI ', 'CM', 'CAMI                                                                   '],
            ['CAMIN', 'CM', 'CAMIN                                                                  '],
            ['CAMPA', 'CP', 'CAMPA                                                                  '],
            ['CAMPG', 'CG', 'CAMPING                                                                '],
            ['CAMPO', 'CP', 'CAMPO                                                                  '],
            ['CANÑO', 'KÑ', 'CANTIÑO                                                                '],
            ['CANAL', 'CA', 'CANAL                                                                  '],
            ['CANT ', 'CQ', 'CANTON                                                                 '],
            ['CANTI', 'QT', 'CANTINA                                                                '],
            ['CANTO', 'CQ', 'CANTO                                                                  '],
            ['CANTR', 'QA', 'CANTERA                                                                '],
            ['CARRA', 'QD', 'CARRERADA                                                              '],
            ['CARRE', 'CL', 'CARRER                                                                 '],
            ['CARRY', 'VR', 'CARRERANY                                                              '],
            ['CASA ', 'CS', 'CASA                                                                   '],
            ['CBTIZ', 'CB', 'COBERTIZO                                                              '],
            ['CCVCN', 'CV', 'CIRCUNVALACION                                                         '],
            ['CELLA', 'QN', 'CANELLA                                                                '],
            ['CERRO', 'CE', 'CERRO                                                                  '],
            ['CHLET', 'CH', 'CHALET                                                                 '],
            ['CINT ', 'CI', 'CINTURO                                                                '],
            ['CINT ', 'CI', 'CINTURON                                                               '],
            ['CINY ', 'CI', 'CINYELL                                                                '],
            ['CIRCU', 'CV', 'CIRCUNVALACION                                                         '],
            ['CJLA ', 'CU', 'CALLEJUELA                                                             '],
            ['CJTO ', 'CN', 'CONJUNTO                                                               '],
            ['CLEYA', 'CY', 'CALEYA                                                                 '],
            ['CLLJA', 'CJ', 'CALLEJA                                                                '],
            ['CLLON', 'CK', 'CALLEJON                                                               '],
            ['CLLZO', 'KZ', 'CALLIZO                                                                '],
            ['CLYON', 'KY', 'CALEYON                                                                '],
            ['CMÑO ', 'CM', 'CAMIÑO                                                                 '],
            ['CMNET', 'CM', 'CAMINET                                                                '],
            ['CMNO ', 'CM', 'CAMINO                                                                 '],
            ['CNLLA', 'QN', 'CANELLA                                                                '],
            ['CNVT ', 'CW', 'CONVENT                                                                '],
            ['CNVTO', 'CW', 'CONVENTO                                                               '],
            ['COL  ', 'CO', 'COLONIA                                                                '],
            ['COMPJ', 'QJ', 'COMPLEJO                                                               '],
            ['COOP ', 'KP', 'COOPERATIVA                                                            '],
            ['COSTA', 'KO', 'COSTA                                                                  '],
            ['COSTE', 'KR', 'COSTERA                                                                '],
            ['CRA  ', 'KA', 'CARRERA                                                                '],
            ['CRCRO', 'CC', 'CRUCEIRO                                                               '],
            ['CRLLO', 'RL', 'CORRILLO                                                               '],
            ['CRO  ', 'QR', 'CARRERO                                                                '],
            ['CRRAL', 'QL', 'CORRAL                                                                 '],
            ['CRRAL', 'QL', 'CORRALO                                                                '],
            ['CRRCI', 'KD', 'CORREDORCILLO                                                          '],
            ['CRRDA', 'KD', 'CORREDOIRA                                                             '],
            ['CRRDE', 'KD', 'CORREDERA                                                              '],
            ['CRRDO', 'KD', 'CORREDOR                                                               '],
            ['CRRIL', 'KL', 'CARRIL                                                                 '],
            ['CRRLO', 'QO', 'CORRALILLO                                                             '],
            ['CRROL', 'RR', 'CORRIOL                                                                '],
            ['CRROL', 'SD', 'CORRIOL                                                                '],
            ['CRTIL', 'QI', 'CARRETIL                                                               '],
            ['CRTJO', 'KT', 'CORTIJO                                                                '],
            ['CSRIO', 'CS', 'CASERIO                                                                '],
            ['CSTAN', 'KS', 'COSTANILLA                                                             '],
            ['CTRA ', 'CR', 'CARRETERA                                                              '],
            ['CTRIN', 'QE', 'CARRETERIN                                                             '],
            ['CUADR', 'CD', 'CUADRA                                                                 '],
            ['CUEVA', 'QV', 'CUEVA/S                                                                '],
            ['CUSTA', 'CT', 'CUESTA                                                                 '],
            ['CXON ', 'CX', 'CALEXON                                                                '],
            ['CZADA', 'CZ', 'CALZADA                                                                '],
            ['CZADS', 'CÇ', 'CALZADAS                                                               '],
            ['DEMAR', 'DM', 'DEMARCAÇIO                                                             '],
            ['DEMAR', 'DM', 'DEMARCACION                                                            '],
            ['DHSA ', 'DH', 'DEHESA                                                                 '],
            ['DISEM', 'DS', 'DISEMINADO                                                             '],
            ['DISSE', 'DS', 'DISSEMINAT                                                             '],
            ['DRERA', 'DR', 'DREÇERA                                                                '],
            ['EDIFC', 'ED', 'EDIFICIO/S                                                             '],
            ['EIRAD', 'EI', 'EIRADO                                                                 '],
            ['EMPR ', 'ER', 'EMPRESA                                                                '],
            ['ENTD ', 'EP', 'ENTRADA                                                                '],
            ['EPTZA', 'PZ', 'ENPARANTZA                                                             '],
            ['ERREB', 'AR', 'ERREBAL                                                                '],
            ['ERREP', 'CR', 'ERREPIDE                                                               '],
            ['ERRIB', 'VG', 'ERRIBERA                                                               '],
            ['ESC  ', 'EC', 'ESCALA/S                                                               '],
            ['ESCA ', 'EC', 'ESCALERA/S                                                             '],
            ['ESCAL', 'EW', 'ESCALINATA                                                             '],
            ['ESLDA', 'ES', 'ESPALDA                                                                '],
            ['ESPIG', 'EG', 'ESPIGO                                                                 '],
            ['ESTAC', 'EN', 'ESTACIO                                                                '],
            ['ESTCN', 'EN', 'ESTACION                                                               '],
            ['ESTDA', 'EX', 'ESTRADA                                                                '],
            ['ETDEA', 'AV', 'ETORBIDEA                                                              '],
            ['ETXAD', 'GR', 'ETXADI                                                                 '],
            ['ETXAR', 'CK', 'ETXARTE                                                                '],
            ['EXPLA', 'EZ', 'EXPLANADA                                                              '],
            ['EXTRM', 'EM', 'EXTRAMUROS                                                             '],
            ['EXTRR', 'ET', 'EXTRARRADIO                                                            '],
            ['FALDA', 'FD', 'FALDA                                                                  '],
            ['FBRCA', 'FC', 'FABRICA                                                                '],
            ['FINCA', 'FN', 'FINCA                                                                  '],
            ['G.V. ', 'GV', 'GRAN VIA                                                               '],
            ['GAIN ', 'AT', 'GAIN                                                                   '],
            ['GALE ', 'GA', 'GALERIA                                                                '],
            ['GLLZO', 'GZ', 'GALLIZO                                                                '],
            ['GORAB', 'SB', 'GORABIDE                                                               '],
            ['GRANJ', 'GJ', 'GRANJA                                                                 '],
            ['GRUP ', 'GR', 'GRUP                                                                   '],
            ['GRUPO', 'GR', 'GRUPO/S                                                                '],
            ['GTA  ', 'GL', 'GLORIETA                                                               '],
            ['HEGI ', 'HG', 'HEGI                                                                   '],
            ['HIPOD', 'HP', 'HIPODROMO                                                              '],
            ['HIRIB', 'AV', 'HIRIBIDEA                                                              '],
            ['HONDA', 'PY', 'HONDARTZA                                                              '],
            ['HOYA ', 'HY', 'HOYA                                                                   '],
            ['ILLA ', 'IL', 'ILLA                                                                   '],
            ['INDA ', 'IN', 'INDA                                                                   '],
            ['JARD ', 'JR', 'JARDI                                                                  '],
            ['JDIN ', 'JR', 'JARDIN                                                                 '],
            ['JDIN ', 'JR', 'JARDINS                                                                '],
            ['JDINS', 'JR', 'JARDINES                                                               '],
            ['KAI  ', 'ML', 'KAI                                                                    '],
            ['KALE ', 'CL', 'KALEA                                                                  '],
            ['KARIK', 'CJ', 'KARRIK                                                                 '],
            ['KARRE', 'KA', 'KARRERA                                                                '],
            ['KARRI', 'CL', 'KARRIKA                                                                '],
            ['KOSTA', 'KO', 'KOSTA                                                                  '],
            ['KRRIL', 'KL', 'KARRIL                                                                 '],
            ['LAGO ', 'LA', 'LAGO                                                                   '],
            ['LASTE', 'AJ', 'LASTERBIDE                                                             '],
            ['LDERA', 'LD', 'LADERA                                                                 '],
            ['LEKU ', 'LG', 'LEKU                                                                   '],
            ['LLNRA', 'LL', 'LLANURA                                                                '],
            ['LLOC ', 'LG', 'LLOC                                                                   '],
            ['LOMA ', 'LM', 'LOMA                                                                   '],
            ['LOMO ', 'LO', 'LOMO                                                                   '],
            ['LORAK', 'JR', 'LORATEGIAK                                                             '],
            ['LORAT', 'JR', 'LORATEGI                                                               '],
            ['LUGAR', 'LG', 'LUGAR                                                                  '],
            ['MALEC', 'MA', 'MALECON                                                                '],
            ['MASIA', 'MS', 'MASIA/S                                                                '],
            ['MAZO ', 'MZ', 'MAZO                                                                   '],
            ['MENDI', 'MT', 'MENDI                                                                  '],
            ['MERC ', 'MC', 'MERCADO                                                                '],
            ['MERCT', 'MC', 'MERCAT                                                                 '],
            ['MIRAD', 'MD', 'MIRADOR                                                                '],
            ['MOLL ', 'ML', 'MOLL                                                                   '],
            ['MONTE', 'MT', 'MONTE                                                                  '],
            ['MRDOR', 'MD', 'MIRADOR                                                                '],
            ['MTRIO', 'MO', 'MONASTERIO                                                             '],
            ['MUELL', 'ML', 'MUELLE                                                                 '],
            ['NAVE ', 'NV', 'NAVE/S                                                                 '],
            ['NCLEO', 'UN', 'NUCLEO                                                                 '],
            ['NUDO ', 'ND', 'NUDO                                                                   '],
            ['ONDA ', 'PY', 'ONDARTZA                                                               '],
            ['PAGO ', 'PP', 'PAGO                                                                   '],
            ['PALAC', 'PC', 'PALACIO                                                                '],
            ['PANT ', 'P ', 'PANTANO                                                                '],
            ['PARC ', 'PQ', 'PARC                                                                   '],
            ['PARKE', 'PQ', 'PARKE                                                                  '],
            ['PARTI', 'PF', 'PARTICULAR                                                             '],
            ['PAS  ', 'PA', 'PAS                                                                    '],
            ['PASAI', 'PJ', 'PASAIA                                                                 '],
            ['PASEA', 'PS', 'PASEABIDE                                                              '],
            ['PASEA', 'PS', 'PASEALEKUA                                                             '],
            ['PASEO', 'PS', 'PASEO                                                                  '],
            ['PASEO', 'PS', 'PASEO                                                                  '],
            ['PASSE', 'PS', 'PASSEIG                                                                '],
            ['PATIO', 'PK', 'PATIO                                                                  '],
            ['PBDO ', 'PB', 'POBLADO                                                                '],
            ['PBLO ', 'PB', 'PUEBLO                                                                 '],
            ['PDA  ', 'PV', 'PUJADA                                                                 '],
            ['PDIS ', 'PÇ', 'PASSADIS                                                               '],
            ['PG   ', 'PG', 'PG                                                                     '],
            ['PGIND', 'PG', 'POLIGONO INDUST                                                        '],
            ['PINAR', 'PN', 'PINAR                                                                  '],
            ['PISTA', 'PI', 'PISTA                                                                  '],
            ['PJDA ', 'SU', 'PUJADA, SUBIDA                                                         '],
            ['PL   ', 'PL', 'PL                                                                     '],
            ['PLA  ', 'PW', 'PLA                                                                    '],
            ['PLAÇA', 'PZ', 'PLAÇA                                                                  '],
            ['PLAYA', 'PY', 'PLAYA                                                                  '],
            ['PLAZA', 'PZ', 'PLAZA                                                                  '],
            ['PLCET', 'PL', 'PLACETA                                                                '],
            ['PLLOP', 'PX', 'PASILLO                                                                '],
            ['PLZLA', 'PL', 'PLAZUELA                                                               '],
            ['PNTE ', 'PT', 'PUENTE                                                                 '],
            ['POLIG', 'PG', 'POLIGONO                                                               '],
            ['PONT ', 'PT', 'PONT                                                                   '],
            ['PONTE', 'PT', 'PONTE                                                                  '],
            ['PORT ', 'PO', 'PORT                                                                   '],
            ['PQUE ', 'PQ', 'PARQUE                                                                 '],
            ['PRAÑA', 'PÑ', 'PRACIÑA                                                                '],
            ['PRAGE', 'PE', 'PARATGE                                                                '],
            ['PRAIA', 'PY', 'PRAIA                                                                  '],
            ['PRAJE', 'PE', 'PARAJE                                                                 '],
            ['PRAXE', 'PE', 'PARAXE                                                                 '],
            ['PRAZA', 'PZ', 'PRAZA                                                                  '],
            ['PROL ', 'PR', 'PROLONGACIO                                                            '],
            ['PROL ', 'PR', 'PROLONGACION                                                           '],
            ['PRTAL', 'PH', 'PORTAL                                                                 '],
            ['PRTCO', 'PH', 'PORTICO                                                                '],
            ['PRZLA', 'PL', 'PRAZUELA                                                               '],
            ['PSAJE', 'PJ', 'PASAJE                                                                 '],
            ['PSAXE', 'PJ', 'PASAXE                                                                 '],
            ['PSLLO', 'PX', 'PASILLO                                                                '],
            ['PSMAR', 'PM', 'PASEO MARITIMO                                                         '],
            ['PTA  ', 'PU', 'PUERTA                                                                 '],
            ['PTDA ', 'PD', 'PARTIDA                                                                '],
            ['PTGE ', 'PJ', 'PASSATGE                                                               '],
            ['PTILO', 'PO', 'PORTILLO                                                               '],
            ['PTLLO', 'PO', 'PUERTILO                                                               '],
            ['PTO  ', 'PO', 'PUERTO                                                                 '],
            ['PZO  ', 'PÇ', 'PASADIZO                                                               '],
            ['PZTA ', 'PL', 'PLAZOLETA                                                              '],
            ['RABAL', 'AR', 'RABAL                                                                  '],
            ['RACDA', 'RA', 'RACONADA                                                               '],
            ['RACO ', 'RC', 'RACO                                                                   '],
            ['RAMAL', 'RM', 'RAMAL                                                                  '],
            ['RAMPA', 'RP', 'RAMPA                                                                  '],
            ['RAMPA', 'RP', 'RAMPLA                                                                 '],
            ['RAVAL', 'AR', 'RAVAL                                                                  '],
            ['RBLA ', 'RB', 'RAMBLA                                                                 '],
            ['RBRA ', 'RI', 'RIBERA                                                                 '],
            ['RCDA ', 'RN', 'RINCONADA                                                              '],
            ['RCON ', 'RC', 'RINCON                                                                 '],
            ['RENTO', 'RT', 'RENTO                                                                  '],
            ['RESID', 'RS', 'RESIDENCIAL                                                            '],
            ['RIERA', 'AY', 'RIERA                                                                  '],
            ['RONDA', 'RD', 'RONDA                                                                  '],
            ['RTDA ', 'RO', 'ROTONDA                                                                '],
            ['RUA  ', 'RU', 'RUA                                                                    '],
            ['RUELA', 'CU', 'RUELA                                                                  '],
            ['RUERO', 'RE', 'RUEIRO                                                                 '],
            ['SANAT', 'SA', 'SANATORIO                                                              '],
            ['SANTU', 'ST', 'SANTUARIO                                                              '],
            ['SARBI', 'AC', 'SARBIDE                                                                '],
            ['SBIDA', 'SB', 'SUBIDA                                                                 '],
            ['SECT ', 'SC', 'SECTOR                                                                 '],
            ['SEDER', 'SD', 'SENDER                                                                 '],
            ['SEDRA', 'SR', 'SENDERA                                                                '],
            ['SEKT ', 'SC', 'SEKTORE                                                                '],
            ['SEND ', 'SN', 'SENDERO                                                                '],
            ['SENDA', 'SD', 'SENDA                                                                  '],
            ['SVTIA', 'CM', 'SERVENTIA                                                              '],
            ['TALDE', 'GR', 'TALDE                                                                  '],
            ['TOKI ', 'PE', 'TOKI                                                                   '],
            ['TRANS', 'TS', 'TRANSITO                                                               '],
            ['TRAS ', 'TA', 'TRASEIRA                                                               '],
            ['TRAS ', 'TA', 'TRASERA                                                                '],
            ['TRAV ', 'TR', 'TRAVESSERA                                                             '],
            ['TRRNT', 'TO', 'TORRENTE                                                               '],
            ['TRSSI', 'TR', 'TRAVESSIA                                                              '],
            ['TRVA ', 'TR', 'TRAVESIA                                                               '],
            ['TRVAL', 'TV', 'TRANSVERSAL                                                            '],
            ['URB  ', 'UR', 'URBANIZACION                                                           '],
            ['URBAT', 'UR', 'URBANITZACIO                                                           '],
            ['URBAZ', 'UR', 'URBANIZAZIO                                                            '],
            ['VALLE', 'VA', 'VALLE                                                                  '],
            ['VCTE ', 'VD', 'VIADUCTE                                                               '],
            ['VCTO ', 'VD', 'VIADUCTO                                                               '],
            ['VECIN', 'VC', 'VECINDARIO                                                             '],
            ['VEGA ', 'VG', 'VEGA                                                                   '],
            ['VENAT', 'VE', 'VEINAT                                                                 '],
            ['VENLA', 'VN', 'VENELA                                                                 '],
            ['VIA  ', 'VI', 'VIA                                                                    '],
            ['VIAL ', 'VL', 'VIAL                                                                   '],
            ['VIANY', 'SN', 'VIARANY                                                                '],
            ['VILLA', 'V ', 'VILLA                                                                  '],
            ['VREDA', 'VR', 'VEREDA                                                                 '],
            ['VVDAS', 'VV', 'VIVIENDAS                                                              '],
            ['XDIN ', 'JR', 'XARDIN                                                                 '],
            ['ZEHAR', 'ZE', 'ZEARKALETA                                                             '],
            ['ZONA ', 'ZO', 'ZONA                                                                   '],
            ['ZUBI ', 'PT', 'ZUBI                                                                   '],
            ['ZUHAI', 'AB', 'ZUHAIZTI                                                               '],
            ['ZUMAR', 'AL', 'ZUMARDI                                                                            '],
        ];
        foreach ($tiposdevia as $tipodevia) {
            TipoVia::create(['codigo1' => $tipodevia[0], 'codigo2' => $tipodevia[1], 'nombre' => trim($tipodevia[2])]);
        }

    }

}
