<?php

return [
    'class'   => 'shadow-lg',
    'content' => [
        [
            'type'  => 'header',
            'name'  => 'menu.main',
            'brand' => [
                'href'      => '#',
                'logo'      => '',
                'logo_dark' => '',
            ],
        ],
        [
            'type'  => 'nav',
            'items' => [
                ['icon' => 'fa-regular fa-house', 'label' => trans_key('menu.Inicio'), 'route' => 'dashboard'],
                ['icon' => 'fa-regular fa-clock', 'label' => trans_key('menu.Fichar'), 'href' => '#', 'device' => 'mobile'],
                [
                    'type'  => 'group',
                    'icon'  => 'fa-solid fa-building-user',
                    'label' => trans_key('menu.Gestión administrativa'),
                    'can'   => 'gestion-comunidad',
                    'items' => [
                        ['icon' => 'fa-solid fa-city', 'label' => trans_key('menu.Comunidades'), 'route' => 'comunidades.index',
                            'can' => 'comunidad-list'],
                        ['icon' => 'fa-solid fa-industry', 'label' => trans_key('menu.Sociedades'), 'route' => 'sociedades.index',
                            'can' => 'sociedad-list'],
                    ],
                ],
                [
                    'type'  => 'group',
                    'icon'  => 'fa-solid fa-calculator',
                    'label' => trans_key('menu.Gestión contable'),
                    'can'   => 'gestion-contable',
                    'items' => [
                        ['icon' => 'fa-solid fa-building', 'label' => trans_key('menu.Empresas contables'), 'route' => 'empresas-contables.index',
                            'can' => 'empresa-contable-list'],
                        ['icon' => 'fa-solid fa-book', 'label' => trans_key('menu.Cuentas contables'), 'route' => 'cuentas-contables.index',
                            'can' => 'cuenta-contable-list'],
                    ],
                ],
                [
                    'type'  => 'group',
                    'icon'  => 'fa-solid fa-building-columns',
                    'label' => trans_key('menu.Maestros'),
                    'can'   => 'menu-maestros',
                    'device' => 'desktop',
                    'items' => [
                        ['icon' => 'fa-solid fa-building-columns', 'label' => trans_key('menu.Entidades financieras'), 'route' => 'entidades-bancarias.index'],
                        ['icon' => 'fa-solid fa-money-bill', 'label' => trans_key('menu.Formas de pago'), 'route' => 'formas-de-pago.index'],
                        ['icon' => 'fa-solid fa-earth-europe', 'label' => trans_key('menu.Países'), 'route' => 'paises.index'],
                        ['icon' => 'fa-solid fa-calendar-days', 'label' => trans_key('menu.Periodicidades de pago'), 'route' => 'periodicidades.index'],
                        ['icon' => 'fa-solid fa-key', 'label' => trans_key('menu.Tipos de ocupación'), 'route' => 'catalogos.tipo-ocupaciones'],
                        ['icon' => 'fa-solid fa-house-chimney', 'label' => trans_key('menu.Tipos de inmueble'), 'route' => 'catalogos.tipo-inmuebles'],
                        ['icon' => 'fa-solid fa-book', 'label' => trans_key('menu.Tipos de cuenta contable'), 'route' => 'catalogos.tipo-cuenta-contables'],
                        ['icon' => 'fa-solid fa-file-signature', 'label' => trans_key('menu.Estados de presupuesto'), 'route' => 'catalogos.tipo-estado-presupuestos'],
                    ],
                ],
                [
                    'type'  => 'group',
                    'icon'  => 'fa-regular fa-user',
                    'label' => trans_key('menu.Informes'),
                    'can'   => 'menu-informes',
                    'items' => [
                        ['icon' => 'fa-regular fa-house', 'label' => trans_key('menu.Informes generados'), 'href' => '#'],
                    ],
                ],
                ['type' => 'spacer'],
                [
                    'type'  => 'group',
                    'icon'  => 'fa-regular fa-user',
                    'label' => trans_key('menu.Administracion de sistema'),
                    'can'   => 'menu-administracion-sistema',
                    'items' => [
                        ['icon'    => 'fa-regular fa-house', 'label' => trans_key('menu.Empresa'),
                            'can'      => 'sistema-empresa-edit',
                            'route'    => 'sysadmin.empresa.edit',
                            'livewire' => 'administracion-sistema.empresa.editar'],
                        ['icon' => 'fa-regular fa-house', 'label' => trans_key('menu.Usuarios'), 'href' => '#',
                        'can'      => 'sistema-usuarios-list', 'route' => 'sysadmin.usuarios.index',
                            'livewire' => 'administracion-sistema.usuarios.lista'],
                        ['icon'    => 'fa-regular fa-house', 'label'   => trans_key('menu.Personas'),
                            'can'      => 'sistema-personas-list', 'route' => 'sysadmin.personas.index',
                            'livewire' => 'administracion-sistema.personas.lista'],
                        ['icon'    => 'fa-regular fa-house', 'label' => trans_key('menu.Roles'), 'href' => '#',
                            'livewire' => 'administracion-sistema.roles.lista',
                            'route'    => 'sysadmin.roles.index',
                            'can'      => 'role-list'],
                        ['icon'    => 'fa-regular fa-house', 'label' => trans_key('menu.Permisos'),
                            'route'    => 'sysadmin.permisos.index',
                            'can'      => 'permiso-list',
                            'livewire' => 'administracion-sistema.permisos.lista'],
                        ['icon'    => 'fa-solid fa-key', 'label' => trans_key('menu.Tokens de API'),
                            'route'    => 'sysadmin.tokens-api.index',
                            'can'      => 'configuracion-token',
                            'livewire' => 'administracion-sistema.tokens-api.lista'],
                        ['icon'    => 'fa-solid fa-envelope', 'label' => trans_key('menu.Correos enviados'),
                            'route'    => 'sysadmin.correos-enviados.index',
                            'can'      => 'correo-enviado-list',
                            'livewire' => 'administracion-sistema.correos-enviados.lista'],
                        ['icon'    => 'fa-solid fa-vial', 'label' => trans_key('menu.Pruebas de correo'),
                            'route'    => 'sysadmin.pruebas-correo.index',
                            'can'      => 'correo-prueba-enviar',
                            'livewire' => 'administracion-sistema.pruebas-correo.formulario'],
                        ['icon'    => 'fa-solid fa-list-check', 'label' => trans_key('menu.Colas de trabajos'),
                            'route'    => 'sysadmin.jobs.index',
                            'livewire' => 'administracion-sistema.jobs.lista'],
                        ['icon'    => 'fa-regular fa-house', 'label' => trans_key('menu.Copias de seguridad'),
                            'route'    => 'sysadmin.backups.index',
                            'livewire' => 'administracion-sistema.backups.lista'],
                            ['icon'    => 'fa-solid fa-file-import', 'label' => trans_key('menu.Importar comunidad'),
                                'route'    => 'sysadmin.comunidades.importar',
                                'livewire' => 'administracion-sistema.comunidades.importar'],
                    ],
                ],
            ],
        ],
        ['type' => 'spacer'],
        [
            'type'  => 'nav',
            'items' => [
                ['icon' => 'fa-regular fa-gear', 'label' => trans_key('menu.Configuracion'), 'can' => 'global-configuracion', 'action' => 'abrir-configuracion', 'device' => 'desktop'],
            ],
        ],
    ],
];
